language: android
android:
  components:
    # some travis/android magic from https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-22
env:
  - GRADLE_OPTS="-XX:MaxPermSize=512m"
script:
  - make travis
after_success:
  - git config --global user.email "dev@medicmobile.org"
  - git config --global user.name "Travis CI"
  - git tag "v${MEDIC_VERSION_NAME}"
  - git push --tags "https://${github_auth}@github.com/${TRAVIS_REPO_SLUG}" >/dev/null 2>/dev/null
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/outputs/apk/*-release.apk
  skip_cleanup: true
  on:
    tags: true
