language: android
android:
  components:
    # some travis/android magic from https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-22
env:
  - GRADLE_OPTS="-XX:MaxPermSize=512m"
before_script:
  - export VERSION_TO_BUILD="$TRAVIS_TAG"
script:
  - make travis
after_success:
  - git config --global user.email "dev@medicmobile.org"
  - git config --global user.name "Travis CI"
  - git tag "v${MEDIC_VERSION_NAME}"
  - git push --tags "https://${github_auth}@github.com/${TRAVIS_REPO_SLUG}" >/dev/null 2>/dev/null
before_deploy:
  - export MEDIC_PUBLISH_DIR="build/publish/${VERSION_TO_BUILD}"
  - mkdir -p "$MEDIC_PUBLISH_DIR"
  - cp build/outputs/apk/*-debug.apk "$MEDIC_PUBLISH_DIR"
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: s3
  access_key_id: ${s3_access_id}
  secret_access_key:
    secure: ${s3_access_secret}
  bucket: medic-mobile
  local_dir: build/publish
  upload-dir: builds/medic-android
  acl: public_read
