name: Build and test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
#     - name: Run Instrumentation Tests
#       uses: reactivecircus/android-emulator-runner@v2
#       with:
#         cmd: ./gradlew connectedUnbrandedWebviewDebugAndroidTest --stacktrace
#         api: 30
#         tag: default
#         abi: arm64-v8a
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Set up fastlane
      run: gem install fastlane --no-document --quiet
    - name: Unpack secrets
      env:
        ANDROID_SECRETS_KEY: ${{ secrets.ANDROID_SECRETS_KEY }}
        ANDROID_SECRETS_IV: ${{ secrets.ANDROID_SECRETS_IV }}
      run: |
        openssl aes-256-cbc -K $ANDROID_SECRETS_KEY -iv $ANDROID_SECRETS_IV -in secrets.tar.gz.enc -out ./secrets.tar.gz -d
        tar -xf ./secrets.tar.gz
    - name: Assemble unbranded
      uses: maierj/fastlane-action@v1.4.0
      env:
        ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      with:
        lane: build
        options: '{ "flavor": "unbranded" }'
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble app debug APK
        run: bash ./gradlew assembleUndrandedWebviewDebug --stacktrace
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Final check apk
        run: bash ls app/build/outputs/apk/debug

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleUndrandedWebviewDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - name: Final check
        run: bash ls app/build/outputs/apk/androidTest/debug
